#!/bin/python3

import math

def is_leap_year(year):
    """The year must be evenly divisible by 4;
        If the year can also be evenly divided by 100, it is not a leap year;
        unless...
        The year is also evenly divisible by 400. Then it is a leap year."""
    flag = False
    if year % 4 == 0:
        flag = True
        if year % 100 == 0:
            flag = False
            if year % 400 == 0:
                flag = True
    return flag

def years_to_delta_secs(year1,year2):
    days = 0
    if (year1 == year2):
        return 0
    elif (year1 < year2):
        for year in range(year1,year2):
            if is_leap_year(year):
                days -= 366
            else:
                days -= 365
    else:
        for year in range(year2,year1):
            if is_leap_year(year):
                days += 366
            else:
                days += 365
    
    return days_to_secs(days)
    
def months_to_secs(inmonths,inyear):
    months = [31, 28 + int(is_leap_year(inyear)), 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    days = 0
    for month in range(0,inmonths-1):
        days += months[month]
    return (days * 24 * 3600)

def days_to_secs(indays):
    return (indays * 24 * 3600)

def hours_to_secs(inhours):
    return (inhours * 3600)

def minutes_to_secs(inmins):
    return (inmins * 60)

def split_date(date_str):
    return date_str.split()

def time_delta(t1, t2):
    months = {"Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4, "May": 5, "Jun": 6, "Jul": 7, "Aug":8, "Sep":9, "Oct":10, "Nov":11, "Dec":12}
    date1 = split_date(t1) 
    date2 = split_date(t2)
    year  = [int(date1[3]), int(date2[3])]
    month = [months[date1[2]], months[date2[2]]]
    day = [int(date1[1]), int(date2[1])]
    hour = [int(date1[4][:2]), int(date2[4][:2])]
    minute = [int(date1[4][3:5]), int(date2[4][3:5])]
    second = [int(date1[4][6:]), int(date2[4][6:])]
    diff_hour = [-1 * int(date1[5][:3]), -1 * int(date2[5][:3])]
    diff_min = [-1 * int(date1[5][0] + date1[5][-2:]), -1 * int(date2[5][0] + date2[5][-2:])]
    delta = years_to_delta_secs(year[0], year[1]) + months_to_secs(month[0],year[0]) - months_to_secs(month[1],year[1]) + days_to_secs(day[0] - day[1]) + hours_to_secs(hour[0]-hour[1]) + minutes_to_secs(minute[0] - minute[1]) + second[0] - second[1] + hours_to_secs(diff_hour[0] - diff_hour[1]) + minutes_to_secs(diff_min[0] - diff_min[1])
    return str(abs(delta))


if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        t1 = input()
        t2 = input()
        delta = time_delta(t1, t2)
        print("Absolute time different in seconds:{}".format(delta))
